// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjhdtdjscgaesfnwshrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqaGR0ZGpzY2dhZXNmbndzaHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzMxOTksImV4cCI6MjA2OTA0OTE5OX0._hgksx66ZT6M8tpuemZQIVft1d33ECfbpzl6X8joTQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});